# Generated by Django 2.0.4 on 2018-04-19 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futbolista',
            name='entrenador',
        ),
        migrations.AddField(
            model_name='futbolista',
            name='entrenador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='miapp.Entrenador'),
            preserve_default=False,
        ),
    ]
