# Generated by Django 2.0.4 on 2018-04-19 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0003_equipo_entrenador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futbolista',
            name='entrenador',
        ),
    ]
